import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import Header from './Header';
import { Providers } from './Providers';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const fontSans = Rubik({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <Providers>
          <Header /> {children}
        </Providers>
      </body>
    </html>
  );
}
